### ISSUE TITLE
whats etag?

### ISSUE THREAD

**Issue by tbuckl** [waltz/nyc-compstat-api#1]
e.g. "32a5c2e4e67d0a790cd2633f39bb42de"

**Comment by waltz** [comment]
I'm not sure. Where do you see that popping up?

**Comment by waltz** [comment]
I'm going to close this. I think I got rid of this tag logging stuff back in 68af7078a011226fec715dd0a10b79bd943d4494. Feel free to reopen this if you have more questions about interesting looking output!
